[package]
name = "system-monitor"
version = "0.1.0"
authors = ["ben"]
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slint = "1.0"
sysinfo = "0.29.10"

[build-dependencies]
slint-build = "1.0"
