import { Button, VerticalBox , HorizontalBox, GridBox, ListView, Slider, ProgressIndicator} from "std-widgets.slint";

import { SidebarButton } from "sidebar-button.slint";
import { CpuMonitor, CpuMonitorPageAdapter, CpuData } from "tools/cpu-monitor.slint";

export { CpuMonitorPageAdapter, CpuData }

export component AppWindow inherits Window {
    in property <float> cpu-usage;

    property <string> selectedTool: "CPU";

    title: "System Monitor";
    preferred-height: 600px;
    preferred-width: 1000px;
    padding: 0;

    VerticalBox {
        spacing: 0;
        padding: 0;

        HorizontalBox {
            spacing: 0;
            padding: 0;

            Rectangle {
                border-width: 0;
                width: 200px;

                
                VerticalLayout {
                    Text {
                        height: 30px;
                        text: "System Monitor";
                        font-weight: 900;
                        horizontal-alignment: center;
                        vertical-alignment: center;
                    }

                    for data in [
                        {label: "CPU"},
                        {label: "Memory"},
                        {label: "Storage"},
                        {label: "Processes"},
                    ]: SidebarButton {
                        height: 40px;
                        text: data.label;
                        selected: root.selectedTool == data.label;
                        clicked => {
                            root.selectedTool = data.label;
                        }
                    }

                    // for v in CpuMonitorPageAdapter.cpu-data: Text {
                    //     text: "" + v.length;
                    // }

                    Rectangle {
                        vertical-stretch: 1;
                    }
                }
            }

            Rectangle {
                width: 1px;
                background: rgba(255, 255, 255, 0.25);
            }

            // Right Panel
            VerticalLayout {
                spacing: 0;
                horizontal-stretch: 1;
                padding: 8px;
                
                Text {
                    text: root.selectedTool;
                    font-weight: 900;
                    font-size: 24px;
                }

                if root.selectedTool == "CPU" : CpuMonitor { cpu-usage: root.cpu-usage; }

                Rectangle {
                    vertical-stretch: 1;
                }
            }
        }

        Rectangle {
            height: 1px;
            background: rgba(255,255,255,0.25);
        }

        Rectangle {
            border-width: 0;
            height: 20px;
        }
    }
}
